import { Injectable } from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
} from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {
  constructor() {}

  intercept(
    request: HttpRequest<unknown>,
    next: HttpHandler
  ): Observable<HttpEvent<unknown>> {
    const authToken =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyIsImtpZCI6Ik1jN2wzSXo5M2c3dXdnTmVFbW13X1dZR1BrbyJ9.eyJhdWQiOiJjYTdmM2YwYi03ZDkxLTQ4MmMtOGUwOS1jNWQ4NDBkMGVhYzUiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMGUyM2MxMC0wMjQ3LTQ4YzMtODEzMi0zOWY1NGIwMzYzZjcvIiwiaWF0IjoxNzI3MzY5MzMwLCJuYmYiOjE3MjczNjkzMzAsImV4cCI6MTcyNzM3MzYyMSwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhZQUFBQWZGTm9YcEhMR2VwakNQS1RpeEcyMytjZWd1ck5KRVpvT0VLenpSNjJiNHVCcllPclRDM3JCUHBDa05LNzZTcjZlZ0xQd3Zzd1VzeWU1a253WmM4Qng2SGs1Ym1Ob3dnU0JMeXQrdWFISXlBPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiI2ZTAwYjMxZi0wNmQ0LTRjOTMtOGIxNC1lMDhiNTY4YjRhMDQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkFsdmVzIiwiZ2l2ZW5fbmFtZSI6IkJpc21hcmNrIiwiZ3JvdXBzIjpbImU0Y2E1MDEwLWQ3ZDctNDBmNS1iM2MwLTc2NjNlY2YwNWJhMCIsImFjZDNiNTEwLWQzMjgtNDIwMy05Mjk1LTc2NDJhYmZiYzlmOCIsIjhkMjliMDQwLWFhZTUtNDI2NS05ZTM2LWYxZWU5MzdiZGFmMSIsIjY4ZDMyZWQwLTYzNzEtNDUzZS1hZjAyLTkzZWEzYzdhNzEwMiIsIjcxZWZiYmUxLTE2Y2ItNDBjYi1iMzkyLTBhNWZjOTAwMDExMSIsIjBmYWU4OGY4LTgyMmEtNGU3OC04ODYxLWY2YTRiOGUzODU3NiIsIjI1NjVmZmZhLTRmYjctNDg5OC04NDY1LThkZWRjODIzYTJkNSJdLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyODA0OjI5Yjg6NTE3ODoxM2UwOmNjNGQ6ZTk0Mjo4ZjcxOjdjY2UiLCJuYW1lIjoiQmlzbWFjayBBbHZlcyIsIm9pZCI6IjY4NDc3YmNlLTA0NjYtNGIyMi1iMTg4LTBmZGFjODhjYzFkMyIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0zNDc0NDM1NjktMTYzMzI5NTQyLTUyNzQ3MzkxNi0yMDE3NyIsInB1aWQiOiIxMDAzMjAwMzU5REM0ODFBIiwicmgiOiIwLkFVWUFFRHppQUVjQ3cwaUJNam4xU3dOajl3c19mOHFSZlN4SWpnbkYyRURRNnNXOEFQZy4iLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiJvaGdZUWdIS05KWUtIR3V3M0E1Rml3RzJXUUhlOXpQanNvbk9jZlQyalRzIiwidGlkIjoiMDBlMjNjMTAtMDI0Ny00OGMzLTgxMzItMzlmNTRiMDM2M2Y3IiwidW5pcXVlX25hbWUiOiJiaXNtYWMucG9ydGZvbGlvQG1hcmlzdGFicmFzaWwub3JnIiwidXBuIjoiYmlzbWFjLnBvcnRmb2xpb0BtYXJpc3RhYnJhc2lsLm9yZyIsInV0aSI6IjlvdUdtdnczRzBLWFdtU0hvZy1GQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDI2In0.tfUeqbHgoxBbzjrsrqdZT0rYLvQIFipfVplPFnSGU4ql96836PkP2Lw3KL8n7gJYOtKOv_xTGpywBbGs6qvG5_rE0_evj24ZwDNJSg894-JDeqezlKrl0SCLYW3XBYAjS1VM7U-yxqn4KkUd-wbkW-eHT1WPGY_wzURgJteEaIW3i5ATAvrj5-mwuEkt04uRAPLutoW6C98TSM7Me4WemPnlHx-l83khbx1T_IhfjRBZ_UY1bfi8-7hFWHqXFi87gpH0RRAR1L7Lqgol7Mr0CcImHcLZzKRYgQ05vcJBrq9jarmWehF1NK-bG8023Xtx_VSpk4KtnEmCSzwxLF1llA';
    const closeRequest = request.clone({
      setHeaders: {
        Authorization: `Bearer ${authToken}`,
      },
      url: 'https://reqres.in/' + request.url,
    });
    return next.handle(closeRequest);
  }
}
